chore: add 'themeName' option for ElementUiResolver
unplugin/unplugin-vue-components pull request #662
Opened 2023-07-21 04:16 UTC by neterm

### Description

### Linked Issues

### Additional context

2023-07-21 04:29 UTC, sxzz approved these changes

2023-07-21 06:35 UTC, sxzz requested changes

2023-07-21 06:35 UTC, sxzz commented on src/core/resolvers/element-ui.ts
> +   */
Add `@default element-ui/packages/theme-chalk`

2023-07-21 06:35 UTC, sxzz commented on src/core/resolvers/element-ui.ts
> +   * theme name, like '@qzdata/element-theme-qzdata'
```suggestion
   * theme name
```

2023-07-21 06:35 UTC, sxzz commented on src/core/resolvers/element-ui.ts
> +  const { importStyle = 'css', themeName } = options
```suggestion
  const { importStyle = 'css', themeName = 'element-ui/packages/theme-chalk' } = options
```

2023-07-21 06:35 UTC, sxzz commented on src/core/resolvers/element-ui.ts
> +
We can remove `if (themeName) {` check if there's a default value.

2023-07-21 06:35 UTC, sxzz commented on src/core/resolvers/element-ui.ts
> +    if (themeName) {
Same here

2024-05-01 06:45 UTC, antfu commented
Close due to inactive - feel free to bring it back if anyone interested in continue it

2024-05-01 06:45 UTC, closed without merging